const TEAM_CODE_TO_FULL_NAME: {[key: string]: string} = {
  ATL: 'Atlanta Hawks',
  BKN: 'Brooklyn Nets',
  BOS: 'Boston Celtics',
  CHA: 'Charlotte Hornets',
  CHI: 'Chicago Bulls',
  CLE: 'Cleveland Cavaliers',
  DAL: 'Dallas Mavericks',
  DEN: 'Denver Nuggets',
  DET: 'Detroit Pistons',
  GSW: 'Golden State Warriors',
  HOU: 'Houston Rockets',
  IND: 'Indiana Pacers',
  LAC: 'Los Angeles Clippers',
  LAL: 'Los Angeles Lakers',
  MEM: 'Memphis Grizzlies',
  MIA: 'Miami Heat',
  MIL: 'Milwaukee Bucks',
  MIN: 'Minnesota Timberwolves',
  NOP: 'New Orleans Pelicans',
  NYK: 'New York Knicks',
  OKC: 'Oklahoma City Thunder',
  ORL: 'Orlando Magic',
  PHI: 'Philadelphia 76ers',
  PHX: 'Phoenix Suns',
  POR: 'Portland Trail Blazers',
  SAC: 'Sacramento Kings',
  SAS: 'San Antonio Spurs',
  TOR: 'Toronto Raptors',
  UTA: 'Utah Jazz',
  WSH: 'Washington Wizards',
};

export const getTeamNameFromCode = (code: string): string => TEAM_CODE_TO_FULL_NAME[code];

// TODO: Use our own url for these.
const TEAM_CODE_TO_LOGO: {[key: string]: string} = {
  ATL: 'https://content.sportslogos.net/logos/6/220/full/8190_atlanta_hawks-primary-2021.png',
  BKN: 'https://content.sportslogos.net/logos/6/3786/full/137_brooklyn-nets-primary-2013.png',
  BOS: 'https://content.sportslogos.net/logos/6/213/full/boston_celtics_logo_primary_19977628.png',
  CHA: 'https://content.sportslogos.net/logos/6/5120/full/1926_charlotte__hornets_-primary-2015.png',
  CHI: 'https://content.sportslogos.net/logos/6/221/full/chicago_bulls_logo_primary_19672598.png',
  CLE: 'https://content.sportslogos.net/logos/6/222/full/cleveland_cavaliers_logo_primary_2023_sportslogosnet-5369.png',
  DAL: 'https://content.sportslogos.net/logos/6/228/full/3463_dallas_mavericks-primary-2018.png',
  DEN: 'https://content.sportslogos.net/logos/6/229/full/8926_denver_nuggets-primary-2019.png',
  DET: 'https://content.sportslogos.net/logos/6/223/full/detroit_pistons_logo_primary_20185710.png',
  GSW: 'https://content.sportslogos.net/logos/6/235/full/3152_golden_state_warriors-primary-2020.png',
  HOU: 'https://content.sportslogos.net/logos/6/230/full/6830_houston_rockets-primary-2020.png',
  IND: 'https://content.sportslogos.net/logos/6/224/full/4812_indiana_pacers-primary-2018.png',
  LAC: 'https://content.sportslogos.net/logos/6/236/full/los_angeles_clippers_logo_primary_2019_sportslogosnet-3776.png',
  LAL: 'https://content.sportslogos.net/logos/6/237/full/uig7aiht8jnpl1szbi57zzlsh.png',
  MEM: 'https://content.sportslogos.net/logos/6/231/full/4373_memphis_grizzlies-primary-2019.png',
  MIA: 'https://content.sportslogos.net/logos/6/214/full/burm5gh2wvjti3xhei5h16k8e.gif',
  MIL: 'https://content.sportslogos.net/logos/6/225/full/milwaukee_bucks_logo_primary_20165763.png',
  MIN: 'https://content.sportslogos.net/logos/6/232/full/9669_minnesota_timberwolves-primary-2018.png',
  NOP: 'https://content.sportslogos.net/logos/6/4962/full/2681_new_orleans_pelicans-primary-2014.png',
  NYK: 'https://content.sportslogos.net/logos/6/216/full/2nn48xofg0hms8k326cqdmuis.gif',
  OKC: 'https://content.sportslogos.net/logos/6/2687/full/khmovcnezy06c3nm05ccn0oj2.png',
  ORL: 'https://content.sportslogos.net/logos/6/217/full/orlando_magic_logo_primary_20117178.png',
  PHI: 'https://content.sportslogos.net/logos/6/218/full/7034_philadelphia_76ers-primary-2016.png',
  PHX: 'https://content.sportslogos.net/logos/6/238/full/phoenix_suns_logo_primary_20143696.png',
  POR: 'https://content.sportslogos.net/logos/6/239/full/9725_portland_trail_blazers-primary-2018.png',
  SAC: 'https://content.sportslogos.net/logos/6/240/full/4043_sacramento_kings-primary-2017.png',
  SAS: 'https://content.sportslogos.net/logos/6/233/full/2547_san_antonio_spurs-primary-2018.png',
  TOR: 'https://content.sportslogos.net/logos/6/227/full/7024_toronto_raptors-primary-2021.png',
  UTA: 'https://content.sportslogos.net/logos/6/234/full/6749_utah_jazz-primary-2017.png',
  WSH: 'https://content.sportslogos.net/logos/6/219/full/5671_washington_wizards-primary-2016.png',
};

export const getLogoForTeamCode = (code: string): string => TEAM_CODE_TO_LOGO[code];
